# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qlocktwo.ui'
#
# Created: Wed Mar 20 22:17:44 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_QlockTwo(object):
    def setupUi(self, QlockTwo):
        QlockTwo.setObjectName("QlockTwo")
        QlockTwo.resize(269, 436)
        self.centralwidget = QtGui.QWidget(QlockTwo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.port = QtGui.QComboBox(self.groupBox_2)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh = QtGui.QPushButton(self.groupBox_2)
        self.refresh.setCheckable(False)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        self.connect = QtGui.QPushButton(self.groupBox_2)
        self.connect.setObjectName("connect")
        self.horizontalLayout.addWidget(self.connect)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.brightness = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightness.sizePolicy().hasHeightForWidth())
        self.brightness.setSizePolicy(sizePolicy)
        self.brightness.setObjectName("brightness")
        self.gridLayout_2.addWidget(self.brightness, 2, 1, 1, 1)
        self.time = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setObjectName("time")
        self.gridLayout_2.addWidget(self.time, 3, 1, 1, 1)
        self.snake = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snake.sizePolicy().hasHeightForWidth())
        self.snake.setSizePolicy(sizePolicy)
        self.snake.setObjectName("snake")
        self.gridLayout_2.addWidget(self.snake, 2, 0, 1, 1)
        self.draw = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.draw.sizePolicy().hasHeightForWidth())
        self.draw.setSizePolicy(sizePolicy)
        self.draw.setObjectName("draw")
        self.gridLayout_2.addWidget(self.draw, 6, 0, 1, 1)
        self.console = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setObjectName("console")
        self.gridLayout_2.addWidget(self.console, 3, 0, 1, 1)
        self.marquee = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marquee.sizePolicy().hasHeightForWidth())
        self.marquee.setSizePolicy(sizePolicy)
        self.marquee.setObjectName("marquee")
        self.gridLayout_2.addWidget(self.marquee, 4, 0, 1, 1)
        self.infrared = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infrared.sizePolicy().hasHeightForWidth())
        self.infrared.setSizePolicy(sizePolicy)
        self.infrared.setObjectName("infrared")
        self.gridLayout_2.addWidget(self.infrared, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.update = QtGui.QCommandLinkButton(self.centralwidget)
        self.update.setObjectName("update")
        self.verticalLayout_3.addWidget(self.update)
        QlockTwo.setCentralWidget(self.centralwidget)

        self.retranslateUi(QlockTwo)
        QtCore.QMetaObject.connectSlotsByName(QlockTwo)

    def retranslateUi(self, QlockTwo):
        QlockTwo.setWindowTitle(QtGui.QApplication.translate("QlockTwo", "QlockTwo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("QlockTwo", "Verbindung", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("QlockTwo", "Neu laden", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setText(QtGui.QApplication.translate("QlockTwo", "Verbinden", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("QlockTwo", "Apps", None, QtGui.QApplication.UnicodeUTF8))
        self.brightness.setText(QtGui.QApplication.translate("QlockTwo", "Helligkeit", None, QtGui.QApplication.UnicodeUTF8))
        self.time.setText(QtGui.QApplication.translate("QlockTwo", "Zeit", None, QtGui.QApplication.UnicodeUTF8))
        self.snake.setText(QtGui.QApplication.translate("QlockTwo", "Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.draw.setText(QtGui.QApplication.translate("QlockTwo", "Zeichnen", None, QtGui.QApplication.UnicodeUTF8))
        self.console.setText(QtGui.QApplication.translate("QlockTwo", "Konsole", None, QtGui.QApplication.UnicodeUTF8))
        self.marquee.setText(QtGui.QApplication.translate("QlockTwo", "Laufschrift", None, QtGui.QApplication.UnicodeUTF8))
        self.infrared.setText(QtGui.QApplication.translate("QlockTwo", "Infrarot", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("QlockTwo", "Nach Updates suchen...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QlockTwo = QtGui.QMainWindow()
    ui = Ui_QlockTwo()
    ui.setupUi(QlockTwo)
    QlockTwo.show()
    sys.exit(app.exec_())

