# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created: Mon May 13 15:07:53 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_qlocktoo(object):
    def setupUi(self, qlocktoo):
        qlocktoo.setObjectName("qlocktoo")
        qlocktoo.resize(333, 351)
        self.centralwidget = QtGui.QWidget(qlocktoo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connectionbox = QtGui.QGroupBox(self.centralwidget)
        self.connectionbox.setObjectName("connectionbox")
        self.gridLayout = QtGui.QGridLayout(self.connectionbox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.port = QtGui.QComboBox(self.connectionbox)
        self.port.setObjectName("port")
        self.port.addItem("")
        self.port.addItem("")
        self.horizontalLayout.addWidget(self.port)
        self.refresh = QtGui.QPushButton(self.connectionbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon)
        self.refresh.setIconSize(QtCore.QSize(12, 12))
        self.refresh.setCheckable(False)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.connectionbox)
        self.appbox = QtGui.QGroupBox(self.centralwidget)
        self.appbox.setEnabled(False)
        self.appbox.setObjectName("appbox")
        self.gridLayout_2 = QtGui.QGridLayout(self.appbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pattern = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pattern.sizePolicy().hasHeightForWidth())
        self.pattern.setSizePolicy(sizePolicy)
        self.pattern.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pattern.setIcon(icon1)
        self.pattern.setObjectName("pattern")
        self.gridLayout_2.addWidget(self.pattern, 2, 1, 1, 1)
        self.demo = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demo.sizePolicy().hasHeightForWidth())
        self.demo.setSizePolicy(sizePolicy)
        self.demo.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/assets/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.demo.setIcon(icon2)
        self.demo.setObjectName("demo")
        self.gridLayout_2.addWidget(self.demo, 3, 1, 1, 1)
        self.snake = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snake.sizePolicy().hasHeightForWidth())
        self.snake.setSizePolicy(sizePolicy)
        self.snake.setCursor(QtCore.Qt.PointingHandCursor)
        self.snake.setStatusTip("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/assets/circle-blank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snake.setIcon(icon3)
        self.snake.setDefault(False)
        self.snake.setFlat(False)
        self.snake.setObjectName("snake")
        self.gridLayout_2.addWidget(self.snake, 0, 1, 1, 1)
        self.console = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setCursor(QtCore.Qt.PointingHandCursor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/assets/coffee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.console.setIcon(icon4)
        self.console.setObjectName("console")
        self.gridLayout_2.addWidget(self.console, 0, 0, 1, 1)
        self.marquee = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marquee.sizePolicy().hasHeightForWidth())
        self.marquee.setSizePolicy(sizePolicy)
        self.marquee.setCursor(QtCore.Qt.PointingHandCursor)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/assets/text-width.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.marquee.setIcon(icon5)
        self.marquee.setObjectName("marquee")
        self.gridLayout_2.addWidget(self.marquee, 2, 0, 1, 1)
        self.settings = QtGui.QPushButton(self.appbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        self.settings.setCursor(QtCore.Qt.PointingHandCursor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/assets/cogs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon6)
        self.settings.setObjectName("settings")
        self.gridLayout_2.addWidget(self.settings, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.appbox)
        qlocktoo.setCentralWidget(self.centralwidget)

        self.retranslateUi(qlocktoo)
        QtCore.QMetaObject.connectSlotsByName(qlocktoo)

    def retranslateUi(self, qlocktoo):
        qlocktoo.setWindowTitle(QtGui.QApplication.translate("qlocktoo", "QlockToo", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionbox.setTitle(QtGui.QApplication.translate("qlocktoo", "Verbindung", None, QtGui.QApplication.UnicodeUTF8))
        self.port.setItemText(0, QtGui.QApplication.translate("qlocktoo", "Getrennt", None, QtGui.QApplication.UnicodeUTF8))
        self.port.setItemText(1, QtGui.QApplication.translate("qlocktoo", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.appbox.setTitle(QtGui.QApplication.translate("qlocktoo", "Apps", None, QtGui.QApplication.UnicodeUTF8))
        self.pattern.setText(QtGui.QApplication.translate("qlocktoo", "Zeichnen", None, QtGui.QApplication.UnicodeUTF8))
        self.demo.setText(QtGui.QApplication.translate("qlocktoo", "Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.snake.setText(QtGui.QApplication.translate("qlocktoo", "Snake", None, QtGui.QApplication.UnicodeUTF8))
        self.console.setText(QtGui.QApplication.translate("qlocktoo", "Konsole", None, QtGui.QApplication.UnicodeUTF8))
        self.marquee.setText(QtGui.QApplication.translate("qlocktoo", "Laufschrift", None, QtGui.QApplication.UnicodeUTF8))
        self.settings.setText(QtGui.QApplication.translate("qlocktoo", "Einstellungen", None, QtGui.QApplication.UnicodeUTF8))

import assets_rc
