# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qlocktoo/settings/settings.ui'
#
# Created: Sat Mar 22 16:17:01 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.setWindowModality(QtCore.Qt.ApplicationModal)
        settings.resize(294, 527)
        settings.setSizeGripEnabled(False)
        settings.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSyncTime = QtGui.QPushButton(self.groupBox)
        self.btnSyncTime.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSyncTime.setCheckable(False)
        self.btnSyncTime.setObjectName("btnSyncTime")
        self.verticalLayout.addWidget(self.btnSyncTime)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.brightnessMax = QtGui.QSlider(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessMax.sizePolicy().hasHeightForWidth())
        self.brightnessMax.setSizePolicy(sizePolicy)
        self.brightnessMax.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightnessMax.setMaximum(255)
        self.brightnessMax.setProperty("value", 255)
        self.brightnessMax.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessMax.setObjectName("brightnessMax")
        self.gridLayout_3.addWidget(self.brightnessMax, 1, 1, 1, 1)
        self.brightnessMin = QtGui.QSlider(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessMin.sizePolicy().hasHeightForWidth())
        self.brightnessMin.setSizePolicy(sizePolicy)
        self.brightnessMin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightnessMin.setMaximum(255)
        self.brightnessMin.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessMin.setObjectName("brightnessMin")
        self.gridLayout_3.addWidget(self.brightnessMin, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.nightmodeStart = QtGui.QTimeEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nightmodeStart.sizePolicy().hasHeightForWidth())
        self.nightmodeStart.setSizePolicy(sizePolicy)
        self.nightmodeStart.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightmodeStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nightmodeStart.setCalendarPopup(False)
        self.nightmodeStart.setTime(QtCore.QTime(23, 0, 0))
        self.nightmodeStart.setObjectName("nightmodeStart")
        self.gridLayout_2.addWidget(self.nightmodeStart, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.nightmodeEnd = QtGui.QTimeEdit(self.groupBox_2)
        self.nightmodeEnd.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightmodeEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nightmodeEnd.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.nightmodeEnd.setAccelerated(False)
        self.nightmodeEnd.setTime(QtCore.QTime(7, 0, 0))
        self.nightmodeEnd.setObjectName("nightmodeEnd")
        self.gridLayout_2.addWidget(self.nightmodeEnd, 1, 2, 1, 1)
        self.nightmodeBrightness = QtGui.QSlider(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nightmodeBrightness.sizePolicy().hasHeightForWidth())
        self.nightmodeBrightness.setSizePolicy(sizePolicy)
        self.nightmodeBrightness.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightmodeBrightness.setMaximum(255)
        self.nightmodeBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.nightmodeBrightness.setObjectName("nightmodeBrightness")
        self.gridLayout_2.addWidget(self.nightmodeBrightness, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(settings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.secondViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.secondViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.secondViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.secondViewDuration.setObjectName("secondViewDuration")
        self.gridLayout.addWidget(self.secondViewDuration, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.wordclockViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.wordclockViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.wordclockViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wordclockViewDuration.setCurrentSection(QtGui.QDateTimeEdit.MinuteSection)
        self.wordclockViewDuration.setTime(QtCore.QTime(0, 5, 0))
        self.wordclockViewDuration.setObjectName("wordclockViewDuration")
        self.gridLayout.addWidget(self.wordclockViewDuration, 0, 1, 1, 1)
        self.temperatureViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.temperatureViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.temperatureViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureViewDuration.setTime(QtCore.QTime(0, 5, 0))
        self.temperatureViewDuration.setObjectName("temperatureViewDuration")
        self.gridLayout.addWidget(self.temperatureViewDuration, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLoad = QtGui.QPushButton(settings)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.btnSave = QtGui.QPushButton(settings)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)
        settings.setTabOrder(self.btnSyncTime, self.nightmodeStart)
        settings.setTabOrder(self.nightmodeStart, self.nightmodeEnd)

    def retranslateUi(self, settings):
        settings.setWindowTitle(QtGui.QApplication.translate("settings", "Einstellungen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settings", "Zeit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSyncTime.setToolTip(QtGui.QApplication.translate("settings", "Die Uhr wird sich weiterhin mit Frankfurt synchronisieren.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSyncTime.setText(QtGui.QApplication.translate("settings", "PC-Zeit übernehmen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("settings", "Helligkeit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settings", "Maximal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settings", "Minimal:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("settings", "Nachtschaltung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settings", "Bis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings", "Von:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings", "Helligkeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("settings", "Anzeigedauer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settings", "Temperatur:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("settings", "Sekunden:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settings", "Wortuhr:", None, QtGui.QApplication.UnicodeUTF8))
        self.wordclockViewDuration.setDisplayFormat(QtGui.QApplication.translate("settings", "mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("settings", "Laden", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("settings", "Speichern", None, QtGui.QApplication.UnicodeUTF8))

