# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qlocktoo/settings/settings.ui'
#
# Created: Wed Dec 25 18:46:36 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.setWindowModality(QtCore.Qt.ApplicationModal)
        settings.resize(312, 540)
        settings.setSizeGripEnabled(False)
        settings.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(settings)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.syncTime = QtGui.QPushButton(self.groupBox)
        self.syncTime.setFocusPolicy(QtCore.Qt.NoFocus)
        self.syncTime.setCheckable(False)
        self.syncTime.setObjectName("syncTime")
        self.verticalLayout.addWidget(self.syncTime)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.brightnessMinimum = QtGui.QSlider(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessMinimum.sizePolicy().hasHeightForWidth())
        self.brightnessMinimum.setSizePolicy(sizePolicy)
        self.brightnessMinimum.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightnessMinimum.setMaximum(255)
        self.brightnessMinimum.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessMinimum.setObjectName("brightnessMinimum")
        self.gridLayout_3.addWidget(self.brightnessMinimum, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.brightnessMaximum = QtGui.QSlider(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessMaximum.sizePolicy().hasHeightForWidth())
        self.brightnessMaximum.setSizePolicy(sizePolicy)
        self.brightnessMaximum.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightnessMaximum.setMaximum(255)
        self.brightnessMaximum.setProperty("value", 255)
        self.brightnessMaximum.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessMaximum.setObjectName("brightnessMaximum")
        self.gridLayout_3.addWidget(self.brightnessMaximum, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.nightModeStart = QtGui.QTimeEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nightModeStart.sizePolicy().hasHeightForWidth())
        self.nightModeStart.setSizePolicy(sizePolicy)
        self.nightModeStart.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightModeStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nightModeStart.setTime(QtCore.QTime(23, 0, 0))
        self.nightModeStart.setCalendarPopup(False)
        self.nightModeStart.setObjectName("nightModeStart")
        self.gridLayout_2.addWidget(self.nightModeStart, 0, 2, 1, 1)
        self.nightModeEnd = QtGui.QTimeEdit(self.groupBox_2)
        self.nightModeEnd.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightModeEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nightModeEnd.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.nightModeEnd.setAccelerated(False)
        self.nightModeEnd.setTime(QtCore.QTime(7, 0, 0))
        self.nightModeEnd.setObjectName("nightModeEnd")
        self.gridLayout_2.addWidget(self.nightModeEnd, 1, 2, 1, 1)
        self.nightModeBrightness = QtGui.QSlider(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nightModeBrightness.sizePolicy().hasHeightForWidth())
        self.nightModeBrightness.setSizePolicy(sizePolicy)
        self.nightModeBrightness.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nightModeBrightness.setMaximum(255)
        self.nightModeBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.nightModeBrightness.setObjectName("nightModeBrightness")
        self.gridLayout_2.addWidget(self.nightModeBrightness, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(settings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.wordclockViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.wordclockViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.wordclockViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wordclockViewDuration.setTime(QtCore.QTime(0, 5, 0))
        self.wordclockViewDuration.setCurrentSection(QtGui.QDateTimeEdit.MinuteSection)
        self.wordclockViewDuration.setObjectName("wordclockViewDuration")
        self.gridLayout.addWidget(self.wordclockViewDuration, 0, 1, 1, 1)
        self.secondViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.secondViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.secondViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.secondViewDuration.setObjectName("secondViewDuration")
        self.gridLayout.addWidget(self.secondViewDuration, 1, 1, 1, 1)
        self.temperatureViewDuration = QtGui.QTimeEdit(self.groupBox_4)
        self.temperatureViewDuration.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.temperatureViewDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureViewDuration.setTime(QtCore.QTime(0, 5, 0))
        self.temperatureViewDuration.setObjectName("temperatureViewDuration")
        self.gridLayout.addWidget(self.temperatureViewDuration, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)
        settings.setTabOrder(self.syncTime, self.nightModeStart)
        settings.setTabOrder(self.nightModeStart, self.nightModeEnd)

    def retranslateUi(self, settings):
        settings.setWindowTitle(QtGui.QApplication.translate("settings", "Einstelllungen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settings", "Zeit", None, QtGui.QApplication.UnicodeUTF8))
        self.syncTime.setToolTip(QtGui.QApplication.translate("settings", "Die Uhr wird sich weiterhin mit Frankfurt synchronisieren.", None, QtGui.QApplication.UnicodeUTF8))
        self.syncTime.setText(QtGui.QApplication.translate("settings", "PC-Zeit übernehmen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("settings", "Helligkeit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settings", "Minimal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settings", "Maximal:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("settings", "Nachtschaltung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings", "Helligkeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings", "Von:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settings", "Bis:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("settings", "Anzeigedauer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settings", "Wortuhr:", None, QtGui.QApplication.UnicodeUTF8))
        self.wordclockViewDuration.setDisplayFormat(QtGui.QApplication.translate("settings", "mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("settings", "Sekunden:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settings", "Temperatur:", None, QtGui.QApplication.UnicodeUTF8))

